function [Legende]=legende()
import mlreportgen.report.*
import mlreportgen.dom.*
    Legende=Section();
    Legende.Numbered=0;
    Legende.Title=Paragraph('Legende');
        text1=Paragraph('MP (Metabolic Power) [W/kg] o. [J/kg/s]:','Lgnd');
        text2=Paragraph(['Die Metabolic Power beschreibt den aktuellen' ...
            ' Energiebedarf pro Zeiteinheit normiert auf das Körpergewicht' ...
            ' anhand der Messdaten (Distanz, Geschwindigkeit, Beschleunigung).' ...
            ' Der durchschnittliche Wert der Einheit beschreibt somit die' ...
            ' Intensität im gegebenen Zeitraum.']);
        text3=Paragraph('VO2 (Sauerstoffaufnahme bzw. aerobe Energie) [W/kg] o. [ml/min/kg]:','Lgnd');
        text4=Paragraph(['Die Sauerstoffaufnahme wird anhand der MP modelliert.' ...
            ' Während die MP den aktuellen (metabolischen) Energiebedarf darstellt,'...
            ' stellt die VO2 den Anteil der aerob verstoffwechselten Energie dar.'...
            ' Sie passt sich "träge" der MP an. Daher kann sie ebenfalls in der'...
            ' Einheit [J/kg/s]  o. [W/kg/s] angegeben werden. Unter der'...
            ' Annahme eines festgewählten Verhältnis der Verstoffwechselung'...
            ' von Fetten und Kohlenhydraten (hier: 13/87% - RQ = 0,96)'...
            ' kann auf die originäre Einheit [ml/min/kg] Sauerstoff'...
            ' umgerechnet werden.'])
        text5=Paragraph('EDI (Equivalent Distance Index) [%]: ','Lgnd');
        text6=Paragraph(['Der EDI beschreibt das Verhältnis von Gesamtdistanz zur' ...
            ' ED (Equivalent Distance), der Distanz, die mit konstanter' ...
            ' Laufgeschwindigkeit im gegebenen Zeitraum hätte absolviert' ...
            ' werden können. Der EDI ist somit ein Faktor der Aufschluss' ...
            ' über den Intervall-Charakter – je höher, desto' ...
            ' „intermittierender".']);
        text7=Paragraph('Anaerober Index (AI) [%]: ','Lgnd');
        text8=Paragraph(['Der anaerobe Index ist das Verhältnis von Energie,' ...
            ' die über- und unterhalb der individuellen MP4 (Metabolic Power' ...
            ' Schwelle bei 4mmol/L Laktat) umgesetzt wurde. Je höher der Index,' ...
            ' desto mehr Energie muss in intensiven Phasen zunächst über ' ...
            'anaerobe Energiesysteme gepuffert / bereitgestellt werden.']);
        text9=Paragraph('HI Events (Hochintensive Aktionen): ','Lgnd');
        text10=Paragraph(['Die hochintensiven Aktionen (z.B. Sprints) werden ' ...
            'anhand eines Schwellenwertes (MP=55W/kg), ' ...
            'einer Mindestdauer (0,6s) und einer minimalen Dauer zwischen ' ...
            'zwei Aktionen (0,2s) berechnet.']);
        text11=Paragraph('Distanz & Energie an-/aerob: ','Lgnd');
        text12=Paragraph(['Beschreibt die Distanz/Energie, die während hoher ' ...
            'und niedriger MP-Phasen (Schwelle=MP4) zurückgelegte / ' ...
            'umgesetzte Distanz/Energie.']);
text=([text1 text2 text3 text4 text5 text6 text7 text8 text9 text10 text11 text12]);
     add(Legende,text);
end
